### ISSUE TITLE
JCEF builds

### ISSUE THREAD

**Issue by ngallagher** [S1artie/cefbuild#1]
Hi,

I noticed you have created a PR for the official CEF project where you have upgraded the version. Just wondering do you have any public site where your recent JCEF builds can be downloaded in a similar manner to how Spotify have done it (only they don't provide JCEF artefacts)

http://opensource.spotify.com/cefbuilds/index.html 

Thanks,
Niall

**Comment by S1artie** [comment]
Sorry, unfortunately not. I've only partially gone the path of automating builds (not as far as Spotify did apparently) and also I'm just building highly customized versions of CEF and JCEF, with some pretty specific customizations that would never be suitable for the official versions (thus I don't create PRs for them).

However, if you just need a build of official JCEF against official CEF (like from Spotify), that's actually pretty easy to do for yourself on any dev machine.
